enable_modelarts: 0

# Url for modelarts
data_url: "s3://bucket-d/datasets/imagenet"
train_url: "s3://bucket-d/train"
checkpoint_url: 
output_path: "/cache/train"
data_path: "/cache/datasets/imagenet"

# eval datasets
interpolation: 'BILINEAR'
eval_path: '$DATA_PATH/imagenet/val'
eval_image_size: 224
eval_batch_size: 128
eval_interval: 1
eval_offset: -1
eval_num_workers: 12

# load model
pretrained: './checkpoint/hlg_mobile.ckpt'

# network
backbone: 'hlg_mobile'
class_num: 1001
hlg_config_path: 'src.hlg.HLGConfig'

open_profiler: 0

amp_level: "O3"
device_target: 'GPU'