# Builtin Configurations(DO NOT CHANGE THESE CONFIGURATIONS unless you know exactly what you are doing)
enable_modelarts: False
data_url: ""
train_url: ""
ckpt_url: 'ckpt files'
result_url: 'infer result files'
checkpoint_url: ""
device_target: "GPU"
device_num: 1
data_path: "/home/mindspore/dataset/embeddings/"
save_path: "./checkpoint"
ckpt_file: ""
enable_profiling: False
# ==============================================================================
# Training options
# inner_model_config

dataset_name: "miniImageNet"
embedding_crop: "center"
train_on_val: False
inner_unroll_length: 5
finetuning_unroll_length: 5
num_latents: 64
inner_lr_init: 1.0
finetuning_lr_init: 0.001
dropout_rate: 0.3 # parameters
kl_weight: 0.001 # parameters
encoder_penalty_weight: 1E-9 # parameters
l2_penalty_weight: 0.0001 # parameters
orthogonality_penalty_weight: 303.0 # parameters
# ==============================================================================
# outer_model_config

num_classes: 5
num_tr_examples_per_class: 1
num_val_examples_per_class: 15
metatrain_batch_size: 12
metavalid_batch_size: 200
metatest_batch_size: 200
num_steps_limit: int(1e5)
outer_lr: 0.005 # parameters
gradient_threshold: 0.1
gradient_norm_threshold: 0.1
total_steps: 200000

# Model Description
model_name: LEO
file_name: 'leo'
file_format: 'MINDIR'  # ['AIR', 'MINDIR']


---
# Config description for each option
enable_modelarts: 'Whether training on modelarts, default: False'
data_url: 'Dataset url for obs'
train_url: 'Training output url for obs'
data_path: 'Dataset path for local'
output_path: 'Training output path for local'

device_target: 'Target device type'
enable_profiling: 'Whether enable profiling while training, default: False'
