enable_modelarts: True
# Url for modelarts
data_url: ""
train_url: ""
checkpoint_url: ""
# Path for local
run_distribute: False
enable_profiling: False
s3_data_path: "s3://bucket-7769-huanan/mrc/DB/ImageNet/ImageNet.tar"
data_path: "/cache/bucket-7769-huanan/mrc/DB/ImageNet/ImageNet/train/"
output_path: "/cache/train"
load_path: "/cache/checkpoint_path/"
device_target: "Ascend"
checkpoint_path: "./checkpoint/"
checkpoint_file_path: ""

# ==============================================================================
# Training options
optimizer: "adamw"
beta1: 0.9
beta2: 0.999
infer_label: ""
class_num: 1001
batch_size: 128
loss_scale: 256
momentum: 0.9
weight_decay: 0.05
epoch_size: 550
pretrain_epoch_size: 0
save_checkpoint: True
save_checkpoint_epochs: 5
keep_checkpoint_max: 30
warmup_epochs: 40
lr_decay_mode: "cosine"
use_label_smooth: True
label_smooth_factor: 0.1
lr_init: 0
lr_max: 0.001
lr_end: 0.0
lr: 0.001
lars_epsilon: 0.0
lars_coefficient: 0.001
autoaugment: False
randaugment: True
dml: 2
dropout: 0.0
lastbn: 1
weight_standardization: 0
lastfn: 0

net_name: "IsyNet"
dataset: "imagenet2012"
device_num: 1
pre_trained: ""
run_eval: False
eval_dataset_path: ""
parameter_server: False
filter_weight: False
save_best_ckpt: True
eval_start_epoch: 40
eval_interval: 1
enable_cache: False
cache_session_id: ""
mode_name: "GRAPH"
acc_mode: "O0"
conv_init: "XavierUniform"
dense_init: "TruncatedNormal"
jsonFile: "../../json/IsyNet-N3.json"
jsonFileTeacher: "../../json/IsyNet-N3-S2.json"
ema: False


# Help description for each configuration
# enable_modelarts: "Whether training on modelarts, default: False"
# data_url: "Dataset url for obs"
# checkpoint_url: "The location of checkpoint for obs"
# data_path: "Dataset path for local"
# output_path: "Training output path for local"
# load_path: "The location of checkpoint for obs"
# device_target: "Target device type, available: [Ascend, GPU, CPU]"
# enable_profiling: "Whether enable profiling while training, default: False"
# num_classes: "Class for dataset"
# batch_size: "Batch size for training and evaluation"
# epoch_size: "Total training epochs."
# checkpoint_path: "The location of the checkpoint file."
# checkpoint_file_path: "The location of the checkpoint file."
